meta_product_name: "DesignnHub"
meta_title: "DesignnHub - Product tagline"
meta_description: "Relevant description"
meta_image: "banner.jpg" # should exist in `app/assets/images/`
twitter_account: "@designnhub"   # required for Twitter Cards
