meta_product_name: "DesignnHub"
meta_title: "DesignnHub"
meta_description: "Connect & Collaborate with designers globally. DesignnHub also provides the platform and resources to help grow designers' professional careers. Founded in Melbourne 2019."
meta_image: "fb-meta-img.jpg" # should exist in `app/assets/images/`
twitter_account: "@designnhub"   # required for Twitter Cards
